POST http://localhost:8800/api/auth/signup
Content-Type: application/json

{
    "name": "test", "email": "test@gmail.com", "password": "123456"
}

###

POST http://localhost:8800/api/auth/signin
Content-Type: application/json

{
    "name": "test", "password": "123456"
}
###
PUT http://localhost:8800/api/users/632d089f3cd4151495765a44
Content-Type: application/json

{
    "name": "updated"
}
###
DELETE http://localhost:8800/api/users/632d089f3cd4151495765a44
###
GET http://localhost:8800/api/users/find/632d089f3cd4151495765a44